Admin panel
maciejgruszczynski/RubyLoversShop pull request #13
Opened 2020-10-13 21:21 UTC by maciejgruszczynski

2020-10-16 21:41 UTC, oskarlakner commented on app/controllers/admin/application_controller.rb
> +  class ApplicationController < ActionController::Base
lubie kontrolery, aby takie kontrolery dziedziczyly z application controller oraz nazywaly sie BaseController - tak aby sie nie mylilo przy wyszukiwaniu :)

2020-10-16 21:48 UTC, oskarlakner commented on spec/models/admin_user_spec.rb
> +  pending "add some examples to (or delete) #{__FILE__}"
ta specka chyba jest zbedna

2020-10-16 21:48 UTC, oskarlakner commented on spec/models/user_spec.rb
> +  pending "add some examples to (or delete) #{__FILE__}"
tak samo

2020-10-16 21:48 UTC, oskarlakner commented on spec/support/devise.rb
> +end
polecam poprawic ustawienia edytora :)

2020-10-16 21:52 UTC, oskarlakner commented on spec/system/admin/order_spec.rb
> +      order.save!
dlaczego zapisujesz ten order?

2020-10-16 22:24 UTC, maciejgruszczynski commented on spec/system/admin/order_spec.rb
> +      order.save!
@oskarlakner jeśli nie będzie zapisany - to w teście systemowym nie pokazuje się na stronie - nie możesz mieć asercji opartej o ten order

2020-10-17 19:53 UTC, oskarlakner commented on spec/system/admin/order_spec.rb
> +      order.save!
a sprobuj w L#5 dac let! ;)

2020-10-17 22:48 UTC, maciejgruszczynski commented on spec/support/devise.rb
> +end
hmm to ciekawe bo rubocop nic mi nie sygnalizowal tutaj...

2020-10-17 22:50 UTC, maciejgruszczynski commented on spec/system/admin/order_spec.rb
> +      order.save!
dziala...a tak dlugo zylem w przekonaniu ze trzeba ta zmienna zapisac.... :)

2020-10-18 20:53 UTC, nikos83 commented on spec/system/admin/order_spec.rb
> +      end
brakuje mi tu chyba specki która przetestuje filtrowanie - czy działa

2020-10-18 20:54 UTC, nikos83 commented on Gemfile
> +gem 'aasm'
przydała by sie wersja gema

2020-10-18 20:54 UTC, nikos83 commented on Gemfile
> +gem 'devise'
jak wyzej brakuje wersji gemow

2020-10-18 20:57 UTC, nikos83 requested changes
- wersje gemów dopisać
- brakująca specka ktora testuje filtrowanie

2020-10-19 21:02 UTC, oskarlakner commented on Gemfile
> +gem 'aasm'
dlaczego?

2020-10-19 21:12 UTC, nikos83 commented on Gemfile
> +gem 'aasm'
> dlaczego?

Zakładam, że za kilka miesięcy aasm zostanie zmodyfikowany bez wersji w repo może spowodować błędy w działaniu aplikacji. ~> 5.1.1.

2020-10-20 17:46 UTC, oskarlakner approved these changes

2020-10-22 12:56 UTC, merged

2020-10-25 16:37 UTC, jkojro commented on spec/models/order_spec.rb
> +      it { expect(order).to have_state(:waiting_for_payment).on(:state) }
To takie czepianie się, ale czy to testuje kod, czy sprawdza stan początkowy przed faktycznymi testami? Mi się wydaje, że to drugie i też nie do końca, bo state jest przypisywany za każdym razem przed każdym testem. Może to jest zbędne?

2020-10-25 16:41 UTC, jkojro commented on app/models/order.rb
> +    state :with_customer_data
poniższe można podać w jednej linii po przecinku

2020-10-25 16:44 UTC, jkojro commented on app/models/order.rb
> +    state :waiting_for_payment
Co się stanie gdy klient przed bramką płatności kliknie dwa razy wstecz żeby zmienić adres? Czy możliwe będzie przejście z `waiting_for_payment` do `with_customer_data`

2020-10-25 16:45 UTC, jkojro commented on app/models/order.rb
> +      transitions from: :with_delivery_method, to: :waiting_for_payment
Co się stanie gdy klient przed bramką płatności kliknie dwa razy wstecz żeby zmienić adres? Czy możliwe będzie przejście z waiting_for_payment do with_customer_data